version: "3.8"

services:
  kserver:
    build: ./kserver
    ports:
      - "8080:8080"
    depends_on:
      - etcd

  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
