name: GolangCI-Lint

on:
  pull_request:

jobs:
  lint:
    name: Run GolangCI-Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      GOLANGCI_LINT_VERSION: v1.62.2 # Global variable for GolangCI-Lint version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4' # Adjust the Go version as needed

      - name: Install GolangCI-Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCI_LINT_VERSION

      - name: Run GolangCI-Lint
        run: |
          cd kmodule && golangci-lint run --timeout=10m
