version: "3"

services:
  node1:
    image: docker:dind
    container_name: node1
    privileged: true
    restart: always
    entrypoint:
      ["/bin/sh", "-c", "chmod +x /scripts/init.sh && /scripts/init.sh"]
    volumes:
      - ./node1/scripts:/scripts
    networks:
      cluster_network:
        ipv4_address: 172.20.0.2

  node2:
    image: docker:dind
    container_name: node2
    privileged: true
    restart: always
    ports:
      - "30080:30080"
    entrypoint:
      ["/bin/sh", "-c", "chmod +x /scripts/init.sh && /scripts/init.sh"]
    volumes:
      - ./node2/scripts:/scripts
    networks:
      cluster_network:
        ipv4_address: 172.20.1.2

networks:
  cluster_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
